apiVersion: scalr.essity.com/v1alpha1
kind: Workspace
metadata:
  name: vimal-workspace-01
spec:
  forProvider:
    name: vimals-workspace-01
    organization: cet-launchpad
    environmentName: env-v0otqrn3npkjd8fqk
    attributes:
      executionMode: "remote"
      iacPlatform: terraform
    tags:
      - "demo"
      - "environment: staging"
  providerConfigRef:
    name: default