apiVersion: iacorchestrator.essity.com/v1alpha1
kind: Runner
metadata:
  name: sample-terraform-runner
  labels:
    app: terraform-runner
    environment: development
spec:
  forProvider:
    name: "my-terraform-runner"
    source: "https://github.com/vimal-vijayan/my-app.git"
    env:
      TF_LOG: "INFO"
      TF_WORKSPACE: "vimals-workspace-01"
    # vars:
    #   cluster_name: "my-k8s-cluster"
    #   node_count: "3"
    #   instance_type: "t3.medium"
    #   environment: "development"
  providerConfigRef:
    name: default