apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: scalr-provider-secret
type: Opaque
data:
  credentials: ""

---
apiVersion: scalr.essity.com/v1alpha1
kind: ProviderConfig
metadata:
  name: default 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: scalr-provider-secret
      key: credentials
